version: 2

sources:
  - name: bronze
    database: contoso
    schema: bronze
    tables:
      - name: customer
      - name: product
      - name: store
      - name: currency_exchange
      - name: sales
